BoxLayout:
    orientation: 'vertical'

    Label:
        text: "Dungeons & Dragons"
        font_size: '24sp'
        size_hint_y: None
        height: '10dp'  # Altura fixa

    Button:
        text: "Iniciar Jogo"
        size_hint: 0.8, None
        height: '50dp'
        pos_hint: {"center_x": 0.5}
# Configurações de tela
android.presplash_orientation = portrait
android.window = true
android.fullscreen = 1
